feat: basic logic converting csv into db
MapColonies/polygon-parts-cli pull request #1
Opened 2023-09-03 15:32 UTC by ronenkapelian

read provided csv file with parts data, addapting + converting + uploading to related polygonParts DB

2023-09-07 14:32 UTC, asafMasa requested changes
Looking Good👍, please mind my remarks

2023-09-07 14:32 UTC, asafMasa commented on config/local.json
> +{
git ignore local file

2023-09-07 14:32 UTC, asafMasa commented on config/local.json
> +{
revert

2023-09-07 14:32 UTC, asafMasa commented on package.json
> +  "description": "",
add description and readme

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +    let linesCounter = 0;
add logs for each phase, for example: 
"Start to read csv data"
"Handling row {n}"
"Insert row {n} to DB"
etc.

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +          if (row[this.columnMappedKeys['classification']] && CLASSIFICATION_MAPPING[row[this.columnMappedKeys['classification']].toLowerCase()]){
why do you only check classification?
recordId for example is also a must - lets talk about required fields

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +                    recordId: row[this.columnMappedKeys['recordid']] ? row[this.columnMappedKeys['recordid']]: 'unknown',
recordId - must be provided

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +                    productType: row[this.columnMappedKeys['producttype']] ? row[this.columnMappedKeys['producttype']]: 'orthophotoBest',
Because recordId - must be provided, i prefer this value will also be provided

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +                    sourceStartDateUtc: row[this.columnMappedKeys['sourcedateend']].replaceAll('/','-'),
bug use "sourcedate**start**"

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +                    minResolutionDegree: parseFloat(row[this.columnMappedKeys['maxresolutiondeg']]),
bug use "**min**resolutiondeg"

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +                    minResolutionMeter: parseFloat(row[this.columnMappedKeys['maxresolutionmeter']]),
bug use "**min**resolutionmeter"

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +          const polygons = this.multiPolygon2Polygons(row[this.columnMappedKeys['wkt']])
throw error if wkt isn't provided

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +  constructHeaders = async () => {
is this method name explains what the method does?

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +  printObjects = () => {
is this method used? where?

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +      let enumerableHeaders = {};
rename this variable name so it will be self explenatory

2023-09-07 14:32 UTC, asafMasa commented on src/dataSource.js
> +    const geoJson = geoParse(wkt);
check that it's realy multi polygon before trying to split it, if its type is polygon take it as is, multi-polygon split to polygons, other types throw an error

2023-09-10 06:07 UTC, ronenkapelian commented on src/dataSource.js
> +                    minResolutionDegree: parseFloat(row[this.columnMappedKeys['maxresolutiondeg']]),
I was discuss with Shaziri, he will provide me only "max" and told me refernce the min the same as max

2023-09-10 06:07 UTC, ronenkapelian commented on src/dataSource.js
> +                    minResolutionMeter: parseFloat(row[this.columnMappedKeys['maxresolutionmeter']]),
I was discuss with Shaziri, he will provide me only "max" and told me refernce the min the same as max

2023-09-10 06:08 UTC, ronenkapelian commented on src/dataSource.js
> +                    sourceStartDateUtc: row[this.columnMappedKeys['sourcedateend']].replaceAll('/','-'),
I was discuss with Shaziri, he will provide me only "end" and told me refernce the "start" the same as "end"

2023-09-10 10:37 UTC, ronenkapelian commented on package.json
> +  "description": "",
done

2023-09-10 10:37 UTC, ronenkapelian commented on src/dataSource.js
> +    let linesCounter = 0;
added

2023-09-10 10:37 UTC, ronenkapelian commented on src/dataSource.js
> +          const polygons = this.multiPolygon2Polygons(row[this.columnMappedKeys['wkt']])
done

2023-09-10 10:37 UTC, ronenkapelian commented on src/dataSource.js
> +                    recordId: row[this.columnMappedKeys['recordid']] ? row[this.columnMappedKeys['recordid']]: 'unknown',
done

2023-09-10 10:37 UTC, ronenkapelian commented on src/dataSource.js
> +    const geoJson = geoParse(wkt);
done

2023-09-10 10:42 UTC, ronenkapelian commented on src/dataSource.js
> +      let enumerableHeaders = {};
removed

2023-09-10 10:42 UTC, ronenkapelian commented on src/dataSource.js
> +  constructHeaders = async () => {
added remarks

2023-09-11 08:03 UTC, asafMasa requested changes
👍 Good Job

2023-09-11 08:03 UTC, asafMasa commented on src/dataSource.js
> +          if (isValidRow) {
you should change the oreder - if !valid - return

2023-09-11 08:03 UTC, asafMasa commented on src/dataSource.js
> +    if (!row[this.columnMappedKeys["wkt"]]) {
you should validate that type is multipolygon or polygon

2023-09-11 08:03 UTC, asafMasa commented on src/dataSource.js
> +                region: row[this.columnMappedKeys["region"]]
make sure sensors array is being recieved with required delimiter

2023-09-11 08:03 UTC, asafMasa commented on src/dataSource.js
> +                  : "unknown",
make sure region array is being recieved with required delimiter

2023-09-12 08:37 UTC, ronenkapelian commented on src/dataSource.js
> +          if (isValidRow) {
replaced and refactored

2023-09-12 11:45 UTC, ronenkapelian commented on src/dataSource.js
> +    if (!row[this.columnMappedKeys["wkt"]]) {
added validation

2023-09-12 11:54 UTC, ronenkapelian commented on src/dataSource.js
> +                region: row[this.columnMappedKeys["region"]]
not on CLI scoop - will implemented on PolygonParts manager service on future

2023-09-12 11:55 UTC, ronenkapelian commented on src/dataSource.js
> +                  : "unknown",
not on CLI scoop - will implemented on PolygonParts manager service on future

2023-09-12 15:09 UTC, asafMasa approved these changes

2023-09-12 15:09 UTC, asafMasa commented on src/dataSource.js
> +      const geoType = wkt.split(" ")[0];
🤮

2023-09-20 12:53 UTC, merged