refactor: typescript and cleanup
MapColonies/polygon-parts-cli pull request #3
Opened 2023-11-07 22:57 UTC by vitaligi

* major refactor of code to typescript
* fixing bugs 
* fixing various edge cases handling
* better flow and error reporting
* overall package sync with boilerplate standarts

2023-11-07 23:00 UTC, vitaligi reviewed
There is some work to be done regarding standardization of fields and documenting them

2023-11-08 09:03 UTC, shimoncohen requested changes

2023-11-08 09:03 UTC, shimoncohen commented on sample_data/polygon_parts_3_sample_geo copy.csv
> +geom,recordId,productId,classification,productType,srsName,description,imageName,minHorizontalAccuracyCe90,minResolutionMeter,maxResolutionMeter,sensors,productName,sourceStartDateUtc,sourceEndDateUt
Remove.

2023-11-08 09:03 UTC, shimoncohen commented on .npmrc
> +engine-strict=true
Please add a line at the end of the file.

2023-11-08 09:03 UTC, shimoncohen commented on .vscode/launch.json
> +}
Please add a line at the end of the file.

2023-11-08 09:03 UTC, shimoncohen commented on config/custom-environment-variables.json
> +}
Please add a line at the end of the file.

2023-11-08 09:03 UTC, shimoncohen commented on config/default.json
> +}
Please add a line at the end of the file.

2023-11-08 09:03 UTC, shimoncohen commented on src/constants.ts
> +};
Please add a line at the end of the file.

2023-11-08 09:03 UTC, shimoncohen commented on src/dataSource.ts
> +      throw new Error(`Failed validation for current row - invalid classification. classification should be: ${Object.keys(CLASSIFICATION_MAPPING)}`);
Please add `should be one of:`.

2023-11-08 09:03 UTC, shimoncohen commented on src/dataSource.ts
> +      throw new Error(`Failed validation for current row - invalid product type. productType should be: ${Object.values(PRODUCT_TYPE_MAPPING)}`);
Please add `should be one of:`

2023-11-08 09:03 UTC, shimoncohen commented on src/dataSource.ts
> +            console.error(`Skipping line ${linesCounter} -- ${errMessage}`);
I am not sure we want to skip rows, maybe we should just fail the whole process completely.
Any "missing" row is a part that should have existed in the exact order that was given (for example: on first insert).

2023-11-08 09:03 UTC, shimoncohen commented on src/dataSource.ts
> +      productVersion: '1.0',
This seems incorrect, we should talk to @asafMasa in order to decide what to do with this field.

2023-11-08 09:03 UTC, shimoncohen commented on src/dataSource.ts
> +      productId: row[columnMappedKeys.productId] ? row[columnMappedKeys.productId] : 'unknown',
Maybe use [shortened trenary](https://stackoverflow.com/a/8884092/11915280)?

2023-11-08 09:03 UTC, shimoncohen commented on src/index.ts
> +}
Please add a line at the end of the file.

2023-11-08 09:03 UTC, shimoncohen commented on src/types.ts
> +};
Please add a line at the end of the file.

2023-11-08 09:03 UTC, shimoncohen commented on src/utilities.ts
> +}
Please add a line at the end of the file.

2023-11-08 09:03 UTC, shimoncohen commented on tsconfig.build.json
> +  }
Please add a line at the end of the file.

2023-11-08 09:03 UTC, shimoncohen commented on tsconfig.json
> +  }
Please add a line at the end of the file.

2023-11-08 17:55 UTC, vitaligi commented on .npmrc
> +engine-strict=true
done

2023-11-08 17:55 UTC, vitaligi commented on sample_data/polygon_parts_3_sample_geo copy.csv
> +geom,recordId,productId,classification,productType,srsName,description,imageName,minHorizontalAccuracyCe90,minResolutionMeter,maxResolutionMeter,sensors,productName,sourceStartDateUtc,sourceEndDateUt
done

2023-11-08 17:55 UTC, vitaligi commented on config/custom-environment-variables.json
> +}
done

2023-11-08 17:55 UTC, vitaligi commented on config/default.json
> +}
done

2023-11-08 17:55 UTC, vitaligi commented on src/constants.ts
> +};
done

2023-11-08 17:55 UTC, vitaligi commented on src/dataSource.ts
> +      throw new Error(`Failed validation for current row - invalid classification. classification should be: ${Object.keys(CLASSIFICATION_MAPPING)}`);
done

2023-11-08 17:55 UTC, vitaligi commented on src/dataSource.ts
> +      throw new Error(`Failed validation for current row - invalid product type. productType should be: ${Object.values(PRODUCT_TYPE_MAPPING)}`);
done

2023-11-08 17:55 UTC, vitaligi commented on src/dataSource.ts
> +            console.error(`Skipping line ${linesCounter} -- ${errMessage}`);
ok behavior changed to fail on exceptions

2023-11-08 17:55 UTC, vitaligi commented on src/dataSource.ts
> +      productVersion: '1.0',
it will be received as an input

2023-11-08 17:55 UTC, vitaligi commented on src/dataSource.ts
> +      productId: row[columnMappedKeys.productId] ? row[columnMappedKeys.productId] : 'unknown',
changed to `??`

2023-11-08 17:55 UTC, vitaligi commented on src/index.ts
> +}
done

2023-11-08 17:55 UTC, vitaligi commented on src/types.ts
> +};
done

2023-11-08 17:55 UTC, vitaligi commented on src/utilities.ts
> +}
done

2023-11-08 17:55 UTC, vitaligi commented on tsconfig.build.json
> +  }
done

2023-11-08 17:55 UTC, vitaligi commented on tsconfig.json
> +  }
done

2023-11-08 23:56 UTC, shimoncohen requested changes

2023-11-08 23:56 UTC, shimoncohen commented on src/dataSource.ts
> +    for (const field of REQUIRED_FIELDS) {
Isn't this a duplicate loop?

2023-11-08 23:56 UTC, shimoncohen commented on src/dataSource.ts
> +          // TODO: Add validation all mandatory fields exist
Don't you do this in `this.validateData`?

2023-11-08 23:56 UTC, shimoncohen commented on src/types.ts
> +export type QQQ = keyof typeof VALIDATION_ERRORS;
Was this meant to be named `QQQ`?

2023-11-09 07:42 UTC, vitaligi commented on src/dataSource.ts
> +    for (const field of REQUIRED_FIELDS) {
removed

2023-11-09 07:42 UTC, vitaligi commented on src/dataSource.ts
> +          // TODO: Add validation all mandatory fields exist
removed comment

2023-11-09 07:43 UTC, vitaligi commented on src/types.ts
> +export type QQQ = keyof typeof VALIDATION_ERRORS;
renamed

2023-11-09 20:08 UTC, shimoncohen approved these changes

2023-11-09 20:08 UTC, shimoncohen commented on config/default.json
> +}
Please add a line at the end of the file.

2023-11-09 20:08 UTC, shimoncohen commented on sample_data/polygon_parts_3_sample_geo.csv
> +"MULTIPOLYGON (((35.197864081 32.172485262,35.196364081 32.172485262,35.171864081 32.172485262,35.171864081 32.173985262,35.171864081 32.190485262,35.196364081 32.190485262,35.197864081 32.190485262,
Please add a line at the end of the file.

2023-11-09 20:08 UTC, shimoncohen commented on src/index.ts
> +}
Please add a line at the end of the file.

2023-11-12 11:02 UTC, asafMasa requested changes, later dismissed
Keep up the good job 👍

2023-11-12 11:02 UTC, asafMasa commented on README.md
> +| minHorizontalAccuracyCe90 |   | - | number |
update data by product comments (maxHorizontalAccuracyCe90, etc.)

2023-11-12 11:02 UTC, asafMasa commented on README.md
> +| geom | geometry of feature, may be MultiPolygon or Polygon   | +  | |
explain what the input is (WKT for example)

2023-11-12 11:02 UTC, asafMasa commented on README.md
> +| maxResolutionDegree | used for min also  | - | float |
Please keep data convntion as described in mc-metadata
https://github.com/MapColonies/mc-models/blob/master/src/models/layerMetadata/layerMetadata.ts#L746C8-L746C8
![image](https://github.com/MapColonies/polygon-parts-cli/assets/18442671/67c4cd43-9865-43e7-976c-042ee4296765)

2023-11-12 11:02 UTC, asafMasa commented on README.md
> +| sourceDateEnd | will be used also for "start" | + | YYYY-MM-DD hh:mm:ss|
Please make sure time response format that is returned in same format as in catalog
![image](https://github.com/MapColonies/polygon-parts-cli/assets/18442671/3426b8e9-2e1b-4139-8a01-715d8ce849d1)

2023-11-12 11:02 UTC, asafMasa commented on sample_data/polygon_parts_3_sample_geo.csv
> +geom,recordId,productId,classification,productType,productVersion,srsName,description,imageName,minHorizontalAccuracyCe90,minResolutionMeter,maxResolutionMeter,sensors,productName,sourceStartDateUtc,
Please document all new / updated fields to requirement documentation

2023-11-12 11:02 UTC, asafMasa commented on src/csvToDB.ts
> +      classification: isPartOf(classificationKey, CLASSIFICATION_MAPPING) ? CLASSIFICATION_MAPPING[classificationKey] : undefined,
make sure it's defined or get it from record

2023-11-12 11:02 UTC, asafMasa commented on package.json
> +    "test": "npm run test:unit && npm run test:integration",
do we have tests?

2023-11-12 14:15 UTC, vitaligi commented on package.json
> +    "test": "npm run test:unit && npm run test:integration",
nope, returning back

2023-11-12 15:20 UTC, vitaligi commented on config/default.json
> +}
done

2023-11-12 15:20 UTC, vitaligi commented on sample_data/polygon_parts_3_sample_geo.csv
> +"MULTIPOLYGON (((35.197864081 32.172485262,35.196364081 32.172485262,35.171864081 32.172485262,35.171864081 32.173985262,35.171864081 32.190485262,35.196364081 32.190485262,35.197864081 32.190485262,
done

2023-11-12 15:20 UTC, vitaligi commented on src/index.ts
> +}
done

2023-11-12 15:21 UTC, vitaligi commented on README.md
> +| geom | geometry of feature, may be MultiPolygon or Polygon   | +  | |
done

2023-11-12 15:21 UTC, vitaligi commented on README.md
> +| minHorizontalAccuracyCe90 |   | - | number |
done

2023-11-12 15:22 UTC, vitaligi commented on README.md
> +| maxResolutionDegree | used for min also  | - | float |
restoring to original column names

2023-11-12 15:22 UTC, vitaligi commented on README.md
> +| sourceDateEnd | will be used also for "start" | + | YYYY-MM-DD hh:mm:ss|
it more depends on the WFS server backend

2023-11-12 15:24 UTC, vitaligi commented on sample_data/polygon_parts_3_sample_geo.csv
> +geom,recordId,productId,classification,productType,productVersion,srsName,description,imageName,minHorizontalAccuracyCe90,minResolutionMeter,maxResolutionMeter,sensors,productName,sourceStartDateUtc,
iv'e went back to the previous field names and take values from: `sourceDateEnd`, `maxResolutionDeg`, `maxResolutionMeter`, `minHorizontalAccuracyCE90`

2023-11-12 15:25 UTC, vitaligi commented on src/csvToDB.ts
> +      classification: isPartOf(classificationKey, CLASSIFICATION_MAPPING) ? CLASSIFICATION_MAPPING[classificationKey] : undefined,
passing it to PG, there will be a column with a custom type with classification values

2023-11-12 22:00 UTC, shimoncohen requested changes

2023-11-12 22:00 UTC, shimoncohen commented on src/csvToDB.ts
>        //TODO - start date taken from end
Remove comment.

2023-11-12 22:00 UTC, shimoncohen commented on src/csvToDB.ts
>        //TODO - min res taken from max
Remove comment.

2023-11-12 22:00 UTC, shimoncohen commented on src/csvToDB.ts
>        //TODO - min res taken from max
Remove comment.

2023-11-12 22:00 UTC, shimoncohen commented on src/csvToDB.ts
> +      //TODO - min res taken from max
This comment indicates a different approach, remove comment and fix if needed.

2023-11-12 22:00 UTC, shimoncohen commented on src/pg.ts
> +    // const fields = Object.keys(polygon).map(polygon => `'${polygon}'`);
Please remove if not needed.

2023-11-12 22:00 UTC, shimoncohen commented on src/pg.ts
> +    // const fieldsPlaceholders = fields.map((_, index) => `$${index + 1}`);
Please remove if not needed.

2023-11-12 22:00 UTC, shimoncohen commented on src/pg.ts
> +    // const query = `INSERT INTO \'${this.dbConfig.schema}\'.${this.dbConfig.table}(${fields}) VALUES (${fieldsPlaceholders})`;
Please remove if not needed.

2023-11-12 22:31 UTC, vitaligi commented on src/pg.ts
> +    // const query = `INSERT INTO \'${this.dbConfig.schema}\'.${this.dbConfig.table}(${fields}) VALUES (${fieldsPlaceholders})`;
done

2023-11-12 22:31 UTC, vitaligi commented on src/pg.ts
> +    // const fieldsPlaceholders = fields.map((_, index) => `$${index + 1}`);
done

2023-11-12 22:31 UTC, vitaligi commented on src/pg.ts
> +    // const fields = Object.keys(polygon).map(polygon => `'${polygon}'`);
done

2023-11-12 22:31 UTC, vitaligi commented on src/csvToDB.ts
> +      //TODO - min res taken from max
done

2023-11-12 22:31 UTC, vitaligi commented on src/csvToDB.ts
>        //TODO - min res taken from max
done

2023-11-12 22:31 UTC, vitaligi commented on src/csvToDB.ts
>        //TODO - min res taken from max
done

2023-11-12 22:31 UTC, vitaligi commented on src/csvToDB.ts
>        //TODO - start date taken from end
done

2023-12-03 04:41 UTC, shimoncohen requested changes

2023-12-03 04:41 UTC, shimoncohen commented on src/error.ts
> +}
Please add a line at the end of the file.

2023-12-03 04:41 UTC, shimoncohen commented on src/types.ts
>  export type Field = typeof ALL_FIELDS[number];
Please rename to `Fields`.

2023-12-03 04:41 UTC, shimoncohen commented on src/csvToDB.ts
> +    Object.entries(polygonRecord).forEach(([key, value]) => {
Please add TODO to remove this in the future when the data we get won't be inserted manually.

2023-12-03 07:29 UTC, vitaligi commented on src/error.ts
> +}
done

2023-12-03 07:29 UTC, vitaligi commented on src/csvToDB.ts
> +    Object.entries(polygonRecord).forEach(([key, value]) => {
it's still maybe useful behaviour for handling optional fields in future. it only depends on the `OPTIONAL_FIELDS` which can be set to no fields at all

2023-12-03 07:29 UTC, vitaligi commented on src/types.ts
>  export type Field = typeof ALL_FIELDS[number];
as this literal type is used in the context of a possible field name, i think that `Field` provides a clearer meaning to it's usage

2023-12-14 15:34 UTC, shimoncohen approved these changes

2023-12-14 15:36 UTC, shimoncohen commented on src/types.ts
>  export type Field = typeof ALL_FIELDS[number];
No problem!

2023-12-14 15:36 UTC, shimoncohen commented on src/csvToDB.ts
> +    Object.entries(polygonRecord).forEach(([key, value]) => {
Got it, agreed.

2023-12-21 23:15 UTC, shimoncohen requested changes

2023-12-21 23:15 UTC, shimoncohen commented on README.md
> +`DB_INSERT_WKT_GEOMETRY`
Please rename to `DB_INSERT_GEOMETRY_AS_WKT`.

2023-12-21 23:15 UTC, shimoncohen commented on src/csvToDB.ts
> +  private getValue<T extends any[], K extends number | undefined>(row: T, field: K): K extends number ? RowValue<T> : null {
Please leave one line before a function.

2023-12-21 23:15 UTC, shimoncohen commented on src/csvToDB.ts
> +    return typeof field === 'number' ? row.at(field) ?? undefined : null;
This is a little too complicated for one line, please separate the conditions with `if` statement.

2023-12-21 23:15 UTC, shimoncohen commented on src/csvToDB.ts
> +      this.getValue(row, mappedKeys[field])
Missing `;`.

2023-12-21 23:15 UTC, shimoncohen commented on src/csvToDB.ts
> +      this.getValue(row, mappedKeys[field])
Returned value is not used.

2023-12-21 23:15 UTC, shimoncohen commented on src/csvToDB.ts
> +    while (polygons[i]) {
Why not simplify with `for` loops?

2023-12-21 23:15 UTC, shimoncohen commented on src/index.ts
> +  // this may require setting additional access to the user - https://www.postgresql.org/docs/12/functions-admin.html#FUNCTIONS-ADMIN-SIGNAL
What if we won't have the sufficient privileges to do this? Was this checked in `outnet`?

2024-01-01 09:15 UTC, vitaligi commented on README.md
> +`DB_INSERT_WKT_GEOMETRY`
done

2024-01-01 14:43 UTC, vitaligi commented on src/csvToDB.ts
> +  private getValue<T extends any[], K extends number | undefined>(row: T, field: K): K extends number ? RowValue<T> : null {
done

2024-01-02 08:01 UTC, vitaligi commented on src/csvToDB.ts
> +    return typeof field === 'number' ? row.at(field) ?? undefined : null;
done

2024-01-02 08:06 UTC, vitaligi commented on src/csvToDB.ts
> +      this.getValue(row, mappedKeys[field])
removed

2024-01-02 08:06 UTC, vitaligi commented on src/csvToDB.ts
> +      this.getValue(row, mappedKeys[field])
removed line

2024-01-02 08:14 UTC, vitaligi commented on src/csvToDB.ts
> +    while (polygons[i]) {
done

2024-01-02 08:17 UTC, vitaligi commented on src/index.ts
> +  // this may require setting additional access to the user - https://www.postgresql.org/docs/12/functions-admin.html#FUNCTIONS-ADMIN-SIGNAL
i was unable to cancel an ongoing transaction in `outnet`
it might be the cause

2024-01-02 11:59 UTC, vitaligi commented on src/index.ts
> +  // this may require setting additional access to the user - https://www.postgresql.org/docs/12/functions-admin.html#FUNCTIONS-ADMIN-SIGNAL
it might also be affected by the postgis/postgresql version, since i moved to 2.5 locally i could not terminate the transaction

2024-02-03 16:46 UTC, shimoncohen approved these changes

2024-02-03 16:49 UTC, shimoncohen commented on src/index.ts
> +  // this may require setting additional access to the user - https://www.postgresql.org/docs/12/functions-admin.html#FUNCTIONS-ADMIN-SIGNAL
What is the status of this? Did we fix it or is this still an issue?

2024-02-05 17:28 UTC, shimoncohen approved these changes

2024-02-05 17:29 UTC, merged